language: go
go:
    - 1.15.x
    - tip
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
os:
    - linux
script:
    - go test -coverprofile c.out ./lists/... ./maps/... ./queues/... ./stacks/... ./trees/...
after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
